// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK6RrJqDz2A6UyZzKaAfNMCgKxExomF6w',
    appId: '1:738952165904:web:818efc4454c571f842e895',
    messagingSenderId: '738952165904',
    projectId: 'first-project-34ce3',
    authDomain: 'first-project-34ce3.firebaseapp.com',
    storageBucket: 'first-project-34ce3.firebasestorage.app',
    measurementId: 'G-4BQQEYB44V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJkPim5JCzPLEc2v4xZ7fWtXKwIHeBJwE',
    appId: '1:738952165904:android:1106c5d54dfc8d1f42e895',
    messagingSenderId: '738952165904',
    projectId: 'first-project-34ce3',
    storageBucket: 'first-project-34ce3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnIV5N0q1qvhWcHaIV9ka_21LWjUjeoOc',
    appId: '1:738952165904:ios:cfdfda1d38cb50eb42e895',
    messagingSenderId: '738952165904',
    projectId: 'first-project-34ce3',
    storageBucket: 'first-project-34ce3.firebasestorage.app',
    iosBundleId: 'com.example.bloc5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK6RrJqDz2A6UyZzKaAfNMCgKxExomF6w',
    appId: '1:738952165904:web:2a8eefe07b6b2cb042e895',
    messagingSenderId: '738952165904',
    projectId: 'first-project-34ce3',
    authDomain: 'first-project-34ce3.firebaseapp.com',
    storageBucket: 'first-project-34ce3.firebasestorage.app',
    measurementId: 'G-9WQECE2ESQ',
  );
}
